### PR TITLE
Include arm64 arch for linux builds

### PR DESCRIPTION
**Pull request by jamezrin**

### CODE REVIEW

**Comment by jamezrin** [comment]
@dragonwocky what do you think? 
Increases a bit the build time but might be worth it, already tested it locally, and it works.

**Review by dragonwocky — APPROVED** [review]
Sure. Build time isn't fast anyway, so a little extra time isn't that big of a deal. Support for more devices/platforms is always good.
I don't have an arm64 device running Windows either, we could try find someone on Discord to test that?

**Comment by jamezrin** [comment]
I have looked at the state of Windows for Arm64, and it doesn't seem too exciting yet, we can easily enable it in the future if we deem it necessary. Merging this and releasing rev 5

**Comment by viveksh1** [comment]
@jamezrin @dragonwocky 
Any update on providing builds for Windows arm64?

Now that the “Copilot+PC”(Windows ARM) laptops are getting more popular (Microsoft Surface Laptop, Dell XPS 13, HP OmniBook X 14, and more), and that Notion provides builds for arm64 Windows, are there any plans to provide binaries for Notion Repackaged on Windows arm64?

Please try to add support and builds soon so that Notion Repackaged can be much more usable on Windows on ARM.

Thank you very much.

**Pull request merged**
